{
 "title": "NGINX_Plus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Upstream Server State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginxplus_upstream_server_state",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Connection Accepted [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(nginxplus_connections_accepted[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Zone Request [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_requests[1m])",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Zone Response [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_responses[1m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Request Total [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(nginxplus_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "HTTP Request Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "nginxplus_http_requests_current"
    }
   ]
  },
  {
   "title": "SSL Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "nginxplus_ssl_handshakes" }
   ]
  },
  {
   "title": "SSL Handshake Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "nginxplus_ssl_handshakes_failed"
    }
   ]
  },
  {
   "title": "Upstream Server Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "nginxplus_upstream_server_response_time",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Fails [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_fails[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Request [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(nginxplus_upstream_server_requests[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Resp 2xx [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=~\"[2]xx\"}[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Resp 4xx [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=~\"[4]xx\"}[1m])"
    }
   ]
  },
  {
   "title": "Upstream Server Resp 5xx [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=~\"[5]xx\"}[1m])",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}